---
driver:
  name: vagrant
  customize:
    memory: 4500
    ioapic: 'on'
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[elastic::install]
      - recipe[elastic::default]
    attributes:
      elastic:
        dir: '/srv/hops'
        user: 'glassfish'
        default:
          private_ips: ["10.0.2.15"]
          public_ips: ["10.0.2.15"]
          private_ips: ["10.0.2.15"]
          public_ips: ["10.0.2.15"]
        kagent:
          user: 'glassfish'
          private_ips: ["10.0.2.15"]
          public_ips: ["10.0.2.15"]
        private_ips: ["10.0.2.15"]
        public_ips: ["10.0.2.15"]



        vagrant: true
